[integator]
fail_fast = false
push_on_success = true
source_dir = "/Users/mabe/Git/iterpy"
skip_if_no_diff_against_trunk = false
trunk = "main"

[[integator.commands]]
name = "Test"
cmd = "mise validate"
max_staleness_seconds = 1
